### ISSUE TITLE
Footer alignment

### ISSUE THREAD

**Issue by itzsaga** [undergroundjs/website#34]
Currently the footer needs some alignment and justification work.
![Screen Shot 2020-01-15 at 07 11 49](https://user-images.githubusercontent.com/11750061/72436851-0e578f80-3767-11ea-954f-8d176ca15eeb.png)

The footer contains three columns in the row and they should be justified accordingly. Left column to the left, center column to the center, right column to the right IMO.

**Comment by kwelch** [comment]
I didn't like the alignment of the years under archive. Also, there will be an additional column once we add back things like speakers, sponsors and schedule. 

For me this was a middle ground between effort and time.

**Comment by itzsaga** [comment]
Word, the copyright is what throws me really. It's just out there by it's lonesome.
