### ISSUE TITLE
Create Link to Tickets on Site

### ISSUE THREAD

**Issue by lapinell** [undergroundjs/website#37]

**Comment by lnbailey** [comment]
I requested access with a gmail account. Using non-gmail is possible but a hassle. I have way too many email addresses.

**Comment by kwelch** [comment]
You could fork and PR as well, if you are familiar with that workflow.

**Comment by kwelch** [comment]
Or message me on discord and I can get your other account access.

**Comment by kwelch** [comment]
Sorry @lnbailey I stole this one, if you want to sync I can ensure you have access and if you I can walk you through the fork and PR process as it is extremely helpful in open source work.
